version: '3.8'

services:
  house-app:
    image: josojmf/house-app:latest
    container_name: house-app
    ports:
      - "5000:5000"
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
      SECRET_KEY: ${SECRET_KEY}
    restart: unless-stopped
